Core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(),
         name='search_results'),
]

GestaoDePraticasDiarias_v6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('', include('Users.urls')),
    path('', include('Activities.urls')),
]

Users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Permission(models.Model):
    id = models.AutoField(db_column='ID',
                          primary_key=True)
    permissionname = models.CharField(db_column='PermissionName',
                                      max_length=255,
                                      blank=True,
                                      null=True)
    permissionactive = models.TextField(db_column='PermissionActive')
    create = models.TextField(db_column='Create')
    read = models.TextField(db_column='Read')
    update = models.TextField(db_column='Update')
    delete = models.TextField(db_column='Delete')
    read_others = models.TextField(db_column='Read_others')
    update_others = models.TextField(db_column='Update_others')

    class Meta:
        managed = True
        db_table = 'Permission'


class Profile(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    profilename = models.CharField(db_column='ProfileName',
                                   max_length=255,
                                   blank=True,
                                   null=True)
    active = models.TextField(db_column='Active')
    userid = models.IntegerField(db_column='UserID')
    permission = models.ManyToManyField('Permission')

    class Meta:
        managed = True
        db_table = 'Profile'


class Organization(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    organizationname = models.CharField(db_column='OrganizationName',
                                        max_length=255,
                                        blank=True,
                                        null=True)
    organizationlocation = models.CharField(db_column='OrganizationLocation',
                                            max_length=255,
                                            blank=True,
                                            null=True)

    class Meta:
        managed = True
        db_table = 'Organization'

    def __str__(self):
        return self.organizationname


class User(AbstractUser):
    id = models.AutoField(db_column='ID', primary_key=True)

    organizationid = models.ForeignKey(Organization,
                                       models.CASCADE,
                                       null=True,
                                       db_column='OrganizationID')
    user_profile = models.ManyToManyField('Profile')
    username = models.CharField(db_column='UserName',
                                max_length=255,
                                unique=True,
                                blank=True,
                                null=True)
    useremail = models.CharField(db_column='UserEmail',
                                 max_length=255,
                                 blank=True,
                                 null=True)
    password = models.CharField(db_column='Password',
                                max_length=255,
                                blank=True,
                                null=True)
    userrole = models.CharField(db_column='UserRole',
                                max_length=255,
                                blank=True,
                                null=True)
    active = models.TextField(db_column='Active')

    class Meta:
        managed = True
        db_table = 'User'

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Activity(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    activityname = models.CharField(db_column='ActivityName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    processid = models.ForeignKey('Process', models.DO_NOTHING, db_column='ProcessID')  # Field name made lowercase.
    descriçào = models.CharField(db_column='Descriçào', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Activity'


class ActivityPattern(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    patternid = models.ForeignKey('Pattern', models.DO_NOTHING, db_column='PatternID')  # Field name made lowercase.
    activityid = models.ForeignKey(Activity, models.DO_NOTHING, db_column='ActivityID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Activity-Pattern'


class ActivityRole(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    activityid = models.ForeignKey(Activity, models.DO_NOTHING, db_column='ActivityID')  # Field name made lowercase.
    roleid = models.ForeignKey('Role', models.DO_NOTHING, db_column='RoleID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Activity-Role'


class Group(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserID')  # Field name made lowercase.
    groupname = models.CharField(db_column='GroupName', unique=True, max_length=255, blank=True, null=True)  # Field name made lowercase.
    creationdate = models.DateField(db_column='CreationDate', blank=True, null=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Group'


class GroupPattern(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    patternid = models.ForeignKey('Pattern', models.DO_NOTHING, db_column='PatternID')  # Field name made lowercase.
    groupid = models.ForeignKey(Group, models.DO_NOTHING, db_column='GroupID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Group-Pattern'


class GroupTags(models.Model):
    groupid = models.ForeignKey(Group, models.DO_NOTHING, db_column='GroupID', primary_key=True)  # Field name made lowercase.
    tagsid = models.ForeignKey('Tags', models.DO_NOTHING, db_column='TagsID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Group_Tags'
        unique_together = (('groupid', 'tagsid'),)


class Organization(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    organizationname = models.CharField(db_column='OrganizationName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    organizationlocation = models.CharField(db_column='OrganizationLocation', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Organization'


class Pattern(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserID')  # Field name made lowercase.
    patternname = models.CharField(db_column='PatternName', max_length=255)  # Field name made lowercase.
    image = models.TextField(db_column='Image', blank=True, null=True)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=255)  # Field name made lowercase.
    data_creation = models.DateField(db_column='Data Creation')  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'Pattern'


class Permission(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    permissionname = models.CharField(db_column='PermissionName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    permissionactive = models.TextField(db_column='PermissionActive')  # Field name made lowercase. This field type is a guess.
    create = models.TextField(db_column='Create')  # Field name made lowercase. This field type is a guess.
    read = models.TextField(db_column='Read')  # Field name made lowercase. This field type is a guess.
    update = models.TextField(db_column='Update')  # Field name made lowercase. This field type is a guess.
    delete = models.TextField(db_column='Delete')  # Field name made lowercase. This field type is a guess.
    read_others = models.TextField(db_column='Read_others')  # Field name made lowercase. This field type is a guess.
    update_others = models.TextField(db_column='Update_others')  # Field name made lowercase. This field type is a guess.

    class Meta:
        managed = False
        db_table = 'Permission'


class Process(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    processname = models.CharField(db_column='ProcessName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserID')  # Field name made lowercase.
    data_criação = models.DateField(db_column='Data Criação')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    descrição = models.CharField(db_column='Descrição', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Process'


class Product(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    productname = models.CharField(db_column='ProductName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    tipo = models.CharField(db_column='Tipo', max_length=1)  # Field name made lowercase.
    formato = models.CharField(db_column='Formato', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Product'


class ProductActivity(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    activityid = models.ForeignKey(Activity, models.DO_NOTHING, db_column='ActivityID')  # Field name made lowercase.
    productid = models.ForeignKey(Product, models.DO_NOTHING, db_column='ProductID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Product-Activity'


class Profile(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    profilename = models.CharField(db_column='ProfileName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    active = models.TextField(db_column='Active')  # Field name made lowercase. This field type is a guess.
    userid = models.IntegerField(db_column='UserID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Profile'


class ProfilePermission(models.Model):
    profileid = models.ForeignKey(Profile, models.DO_NOTHING, db_column='ProfileID', primary_key=True)  # Field name made lowercase.
    permissionid = models.ForeignKey(Permission, models.DO_NOTHING, db_column='PermissionID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Profile_Permission'
        unique_together = (('profileid', 'permissionid'),)


class Role(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    rolename = models.CharField(db_column='RoleName', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Role'


class RoleProduct(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    productid = models.ForeignKey(Product, models.DO_NOTHING, db_column='ProductID')  # Field name made lowercase.
    roleid = models.ForeignKey(Role, models.DO_NOTHING, db_column='RoleID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Role-Product'


class Sentence(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserID')  # Field name made lowercase.
    sentencename = models.CharField(db_column='SentenceName', max_length=255)  # Field name made lowercase.
    datecreated = models.DateField(db_column='DateCreated')  # Field name made lowercase.
    subject = models.CharField(db_column='Subject', max_length=255)  # Field name made lowercase.
    receiver = models.CharField(db_column='Receiver', max_length=255, blank=True, null=True)  # Field name made lowercase.
    datarealizado = models.DateField(db_column='DataRealizado')  # Field name made lowercase.

templates/main/header.html
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/googleapis.css' %}">
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jQuery.js' %}" ></script>
    <!-- Font Awesome JS -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <link rel='icon' href='favicon.ico' type='image/x-icon' sizes="16x16" />
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
</head>
{% block navbar %}
{% endblock %}

templates/main/home.html
 {% extends "main/navbar.html" %}
 {% block title %}Página inicial{% endblock %}
 {% block content %}
	<div class="container">
        <!--{% if perms.Users.add_user %}
            {% include "tables/user.html" with object_list=users %}
        {% endif %}-->
        {% if perms.Activities.add_sentence %}
            {% include "tables/sentence.html" with object_list=sentences %}
        {% endif %}
        {% if perms.Activities.add_group %}
            {% include "tables/group.html" with object_list=groups %}
        {% endif %}
        {% if perms.Activities.add_pattern %}
            {% include "tables/pattern.html" with object_list=patterns %}
        {% endif %}
        <!--{% if perms.Processes.add_process %}
            {% include "tables/process.html" with object_list=processes %}
        {% endif %}
        {% if perms.Processes.add_activity %}
            {% include "tables/activity.html" with object_list=activities %}
        {% endif %}-->
	</div>
{% endblock %}

templates/main/modal.html
<div class="modal fade" data-backdrop="static" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form id="f" class="ajax" method="post">
                <div class="modal-body" id="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="text-danger mr-3" href="" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn text-white">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>


<div class="modal fade" data-backdrop="static" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form id="del" class="ajax" method="post">
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="text-danger mr-3" href="" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn text-white">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" data-backdrop="static" id="Searchmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form class="ajax" method="get" action="{% url 'search_results' %}">
                <div class="modal-body" id="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="text-danger mr-3" href="" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn text-white">Pesquisar</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/main/navbar.html
{% extends "main/header.html" %}

{% block navbar %}
<body>
<div class="wrapper">
    <nav id="sidebar" class="navbar-info" style="background:#058096;">
        <div class="sidebar-header" style="background:#058096;">
            <h4 class="text-white">REGISTO DIÁRIO</h4>
        </div>
        <ul class="list-unstyled components text-white">
            <li {% if request.path == "/" %} class="active" {% endif %}>
                <a href='{% url "home" %}' style="margin-top:10px;"><i class="material-icons">home</i> PÁGINA INICIAL</a>
            </li>
        </ul>
        <ul class="list-unstyled components text-white">
                {% include "main/sidebar/frase.html" %}
                {% include "main/sidebar/agrupamento.html" %}
                {% include "main/sidebar/padrao.html" %}
                {% include "main/sidebar/processo.html" %}
        </ul>
	</nav>
	<div id="content">
		<nav class="navbar navbar-expand-lg navbar-light">
			<button type="button" id="sidebarCollapse" class="btn text-white" style="background:#058096;"><!--btm-info-->
				<i class="fas fa-align-left"></i>
			</button>
			<div class="navegation">
				<h1 class="titulo-principal mt-2"> {% block title %}{{ page.title }}{% endblock %}</h1>
			</div>
			<button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
				<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <button type="button" href="#" class="btn float-right text-white" data-toggle="modal" onclick='newModal("{% url "search" %}", "Pesquisa Avançada", "#Searchmodal", "modal-lg")'>Pesquisa Avançada <i class="fa fa-search"></i></button>
                    </li>
					<li class="nav-item">
						<div class="btn-group">
							<button type="button" class="btn btn-warning text-left dropdown-toggle" style="width:100px;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">+ Novo </button>
							<div class="dropdown-menu dropdown-menu-right">
								{% include "main/topbar/utilizador.html" %}
								{% include "main/topbar/frase.html" %}
								{% include "main/topbar/verbo.html" %}
                                {% include "main/topbar/recurso.html" %}
                                {% include "main/topbar/artefacto.html" %}
								{% include "main/topbar/agrupamento.html" %}
								{% include "main/topbar/padrao.html" %}
								{% include "main/topbar/processo.html" %}
								{% include "main/topbar/atividade.html" %}
                                {% include "main/topbar/papel.html" %}
                                {% include "main/topbar/produto.html" %}
							</div>
						</div>
					</li>

					<li class="nav-item dropdown">
						<a class="nav-link text-left text-dark" style="font-size:1em;" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }}<i class="fas fa-angle-down"></i> </i></a>
						<div class="dropdown-menu dropdown-menu-right">
							<a class="dropdown-item" href="#">Mensagens</a>
							<a class="dropdown-item" href="#">Contactos</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Gerir conta</a>
							<a class="dropdown-item" href="#">Definições</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'logout' %}">Terminar sessão</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>
			{% block content %}
			{% endblock %}
	</div>
    {% include "main/modal.html" %}
</body>
{% include "main/scripts.html" %}
{% endblock %}

templates/main/scripts.html
<script>
    $(".markerDiv").click(function () {
        if(event.srcElement.id == "noCheck"){
            return;
        }
        var $checks = $(this).find('input:checkbox[name=markerType]');
        $checks.prop("checked", !$checks.is(":checked"));
        var boxes = ($('input[name=markerType]:checked'))
        if(boxes.length > 0){
            $('.newChecked').show();
        }
        else{
            $('.newChecked').hide();
        }
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar').toggleClass('active');
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function(e){
        $('.search-panel .dropdown-menu').find('a').click(function(e) {
            e.preventDefault();
            var param = $(this).attr("href").replace("#","");
            var concept = $(this).text();
            $('.search-panel span#search_concept').text(concept);
            $('.input-group #search_param').val(param);
        });
    });
</script>
<script>
    function newModal(url, titulo, modal, size, id="#f"){
        var myNode = document.getElementById("modal-body");
        while (myNode.firstChild) {
            myNode.removeChild(myNode.firstChild);
        }
        $(".modal-dialog").removeClass("modal-lg");
        $(id).attr('action', url);
        $(".modal-dialog").addClass(size);
        try{
            var x = document.getElementById("sentenceTable");
            x.style.display = "none"
        }catch{}
        var btn = $(this);
        var items = $("table input:checkbox:checked").map(function () {
            return $(this).attr('id');
        }).get();
        $.ajax({
            url: url,
            type: 'GET',
            dataType:'json',
            data:{
                'id': items,
            },
            beforeSend: function(data){
                if(url == "/create_group/" || url == "/create_pattern/"){
                    if(url == "/create_group/"){title = "Frases";}else{title = "Agrupamentos";}
                    //container
                    var cont = document.createElement('div');
                    cont.className = 'container';
                    cont.id = 'containerModal';
                    $('.modal-body').append(cont);
                    //row
                    var row = document.createElement('div');
                    row.className = 'row';
                    row.id = 'rowModal';
                    $('#containerModal').append(row);
                    //col form
                    var gFo = document.createElement('div');
                    gFo.className = 'col-xl-6 col-lg-6';
                    gFo.id = 'theForm';
                    $('#rowModal').append(gFo);
                    //col table
                    var gFo = document.createElement('div');
                    gFo.className = 'col-xl-6 col-lg-6';
                    gFo.id = 'theTable';
                    $('#rowModal').append(gFo);
                    //form
                    $('#theForm').load(url);
                    //table
                    var tab = document.createElement('table');
                    tab.className = 'table header-fixed table-hover';
                    tab.id = 'myTable';
                    $('#theTable').append(tab);
                    //head table
                    var the = document.createElement('thead');
                    the.id = 'myTableHead';
                    $('#myTable').append(the);
                    //row table
                    var rta = document.createElement('tr');
                    rta.className = 'd-flex';
                    rta.id = 'myTableRow';
                    $('#myTableHead').append(rta);
                    //table title space
                    var tti = document.createElement('th');
                    tti.className = 'col-12';
                    tti.id = 'titleSpace';
                    $('#myTableRow').append(tti);
                    //title text
                    var  tit = document.createTextNode(title);
                    $('#titleSpace').append(tit);
                    //body table
                    var tbo = document.createElement('tbody');
                    tbo.style.cssText = 'max-height:60vh;';
                    tbo.id = 'myTableBody';
                    $('#myTable').append(tbo);
                }
                else{ $('.modal-body').load(url);}
                $('.modal-title').html(titulo);
                $(modal).modal('show');
            },
            success: function(data){
                $.each(data, function(key, value){
                    //row table
                    var rta = document.createElement('tr');
                    rta.className = 'd-flex';
                    rta.id = 'myTableRow'+value.pk;
                    //row table field
                    var rtf = document.createElement('tr');
                    rtf.className = 'd-block col-12 my-2 mb-2';
                    rtf.id = 'myTableRowTd'+value.pk;
                    $('#myTableBody').append(rta);
                    $('#myTableRow'+value.pk).append(rtf);
                    if(url == "/create_group/"){
                    var sentence = document.createTextNode(value.fields.sentencename); $('#myTableRowTd'+value.pk).append(sentence);}
                    else if(url == "/create_pattern/"){var group = document.createTextNode(value.fields.groupname); $('#myTableRowTd'+value.pk).append(group);}
                });
            },
        });
    } 
</script>
<script>
    $(document).ready(function(){
        $('#f').submit(function() {
            $.ajax({ 
                type: $(this).attr('method'), 
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function(data) {
                    if( data.local == '' ){ window.location.href = '{{ request.path }}'; }
                    else { window.location.href = '../'+data.local; }
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    $(".errorMessage").remove();
                    $("#div_id_"+Object.keys(JSON.parse(xhr.responseText))[0]).append("<div class='errorMessage text-danger'>"+Object.values(JSON.parse(xhr.responseText))[0]+"</div>");
                }
            });
            return false; 
        });
    });
</script>